# Generated by Django 3.0.5 on 2020-06-18 22:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Park',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('neighborhood', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='date of Visit')),
                ('feature', models.CharField(choices=[('w', 'water fountain'), ('s', 'sidewalks'), ('g', 'grassy field'), ('b', 'trashcans'), ('p', 'port-a-potty'), ('t', 'tree shade')], default='w', max_length=1)),
                ('park', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Park')),
            ],
        ),
    ]
