# Generated by Django 3.0.5 on 2020-06-19 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visit',
            name='feature',
        ),
        migrations.AddField(
            model_name='visit',
            name='comment',
            field=models.TextField(default='none', max_length=180),
        ),
    ]
