# Generated by Django 3.0.5 on 2020-06-28 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_visit_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visit',
            old_name='user',
            new_name='user_id',
        ),
    ]
