# Generated by Django 3.0.5 on 2020-06-21 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_auto_20200621_1833'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='park',
            name='user',
        ),
    ]
